### ISSUE TITLE
segfault H2Core::DrumkitComponent::reset_outs on loading song

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#719]
Hydrogen version *          :1.0.0-'24f984a'
Operating system + version  : ubuntu 16.04
Audio driver + version      : jackdmp

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

when switching between the songs in my playlist (using F5/F6) H2 segfaults : 

```
(I) Sample::exec_rubberband_cli ratio: 1.08621, rubberoutframes: 364965, rubberinframes: 336000
(I) SongReader::readSong Reading /home/thijs/.hydrogen/data/songs/hydrogen songs/_BHBM/addicted_v5_seq1_LnV.h2song
(I) Song::Song INIT 'Untitled Song'
(W) LocalFileMng::readXmlString Using default value in drumkit
(W) LocalFileMng::readXmlString Using default value in drumkit
(W) LocalFileMng::readXmlString Using default value in drumkit
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in name
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in name
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in name
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in name
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in name
(W) LocalFileMng::readXmlString Using default value in info
(W) LocalFileMng::readXmlString Using default value in info

Thread 10 "hydrogen" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb023a700 (LWP 14015)]
0x00007ffff7b3b506 in H2Core::DrumkitComponent::reset_outs (this=0xa, 
    nFrames=256)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/b---Type <return> to continue, or q <return> to quit---
asics/drumkit_component.cpp:79
79		memset( __out_L, 0, nFrames * sizeof( float ) );
```

some more gdb output : 

```
(gdb) bt
#0  0x00007ffff7b3b506 in H2Core::DrumkitComponent::reset_outs (this=0xa, nFrames=256)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/basics/drumkit_component.cpp:79
#1  0x00007ffff7ad1eec in H2Core::Sampler::process (this=0xb8c710, nFrames=256, pSong=0x373e9d0)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/sampler/sampler.cpp:117
#2  0x00007ffff7adbb6d in H2Core::audioEngine_process (nframes=256)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/hydrogen.cpp:796
#3  0x00007ffff511dc1e in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#4  0x00007ffff511d058 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#5  0x00007ffff5135680 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#6  0x00007ffff71556ba in start_thread (arg=0x7fffb023a700) at pthread_create.c:333
#7  0x00007ffff5bcc82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

notes 
- this is not easily reproducible
- seems to be related to jack outputs (i'm running in 'per instrument output' mode)
- this is a bug i encountered while hunting down #714

**Comment by thijz** [comment]
have not seen this in a long long time
closing for now
