### ISSUE TITLE
segfault while switching between songs in playlist

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#720]
Hydrogen version *          :1.0.0-'24f984a'
Operating system + version  : ubuntu 16.04
Audio driver + version      : jackdmp

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
i have 10 songs in a playlist.  when i skip between these quickly (using F5/F6) i get this segfault : 
(pasting debug output of 2 different occasions)

segfault 1 : 

```
Thread 10 "hydrogen" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb023a700 (LWP 19365)]
0x00000000005244b8 in std::vector<H2Core::Pattern*, std::allocator<H2Core::Pattern*> >::size (this=0x58) at /usr/include/c++/5/bits/stl_vector.h:655
655	      { return size_type(this->_M_impl._M_finish - this->_M_impl._M_star---Type <return> to continue, or q <return> to quit---~~
t); }
```
backtrace
```
(gdb) bt
#0  0x00000000005244b8 in std::vector<H2Core::Pattern*, std::allocator<H2Core::Pattern*> >::size (this=0x58) at /usr/include/c++/5/bits/stl_vector.h:655
#1  0x000000000052446c in H2Core::PatternList::size (this=0x50)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/include/hydrogen/basics/pattern_list.h:151
#2  0x00007ffff7ae7569 in H2Core::findPatternInTick (nTick=4222, 
    bLoopMode=false, pPatternStartTick=0x7fffb0239b7c)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/hydrogen.cpp:1337
#3  0x00007ffff7ae0f17 in H2Core::Hydrogen::getPosForTick (this=0xb72570, 
    TickPos=4222)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/hydrogen.cpp:2296
#4  0x00007ffff7ae46ea in H2Core::Hydrogen::setTimelineBpm (this=0xb72570)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/hydrogen.cpp:3308
#5  0x00007ffff7b746c5 in H2Core::JackAudioDriver::updateTransportInfo (
    this=0xcd6230)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/IO/jack_audio_driver.cpp:329
#6  0x00007ffff7ae5b39 in H2Core::audioEngine_process_transport ()
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/hydrogen.cpp:601
---Type <return> to continue, or q <return> to quit---
```

segfault 2 : 
```
Thread 10 "hydrogen" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb023a700 (LWP 3414)]
0x00000000005244b8 in std::vector<H2Core::Pattern*, std::allocator<H2Core::Pattern*> >::size (this=0x38) at /usr/include/c++/5/bits/stl_vector.h:655
655	      { return size_type(this->_M_impl._M_finish - this->_M_impl._M_star---Type <return> to continue, or q <return> to quit---~~
t); }

```
backtrace : 
```
(gdb) bt
#0  0x00000000005244b8 in std::vector<H2Core::Pattern*, std::allocator<H2Core::Pattern*> >::size (this=0x38) at /usr/include/c++/5/bits/stl_vector.h:655
#1  0x000000000052446c in H2Core::PatternList::size (this=0x30)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/include/hydrogen/basics/pattern_list.h:151
#2  0x00007ffff7ae7569 in H2Core::findPatternInTick (nTick=19525, 
    bLoopMode=false, pPatternStartTick=0x7fffb0239b7c)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/hydrogen.cpp:1337
#3  0x00007ffff7ae0f17 in H2Core::Hydrogen::getPosForTick (this=0xb72650, 
    TickPos=19525)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/hydrogen.cpp:2296
#4  0x00007ffff7ae46ea in H2Core::Hydrogen::setTimelineBpm (this=0xb72650)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/hydrogen.cpp:3308
#5  0x00007ffff7b746c5 in H2Core::JackAudioDriver::updateTransportInfo (
    this=0xcd6320)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/IO/jack_audio_driver.cpp:329
#6  0x00007ffff7ae5b39 in H2Core::audioEngine_process_transport ()
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/hydrogen.cpp:601
---Type <return> to continue, or q <return> to quit---
#7  0x00007ffff7adb8f6 in H2Core::audioEngine_process (nframes=256)
    at /home/thijs/Music/Hydrogen_Code/hydrogen_thijz_mod_midifix/src/core/src/hydrogen.cpp:758
#8  0x00007ffff511dc1e in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#9  0x00007ffff511d058 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#10 0x00007ffff5135680 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#11 0x00007ffff71556ba in start_thread (arg=0x7fffb023a700) at pthread_create.c:333
#12 0x00007ffff5bcc82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by mauser** [comment]
Hi thijz.

it seems that your version of hydrogen is quite old (24f984a seems to be more then 2 years old). It would be great you could test your recently written issues with a current version of hydrogen. We have fixed a lot of bugs in those areas and it is quite hard to now from the callstacks if those things are still relevant or not.

**Comment by thijz** [comment]
the reason i'm on this old codebase is because this is my laptop for playing live and i dont want to take the risk to upgrade and maybe break my system  :-(
but i totally understand what you mean so will try to reproduce on the latest code
will close this ticket for now
